// All mock file contents for the IDE
var FILES = {};

FILES["payment.controller.ts"] = [
    'import { Request, Response, NextFunction } from \'express\';',
    'import { StripeService } from \'../services/stripe.service\';',
    'import { PaymentValidator } from \'../middleware/payment.validator\';',
    'import { PaymentModel, IPayment } from \'../models/payment.model\';',
    'import { Logger } from \'../utils/logger\';',
    'import { AuthMiddleware } from \'../middleware/auth.middleware\';',
    'import { NotificationService } from \'../services/notification.service\';',
    'import { AppError, ErrorCode } from \'../utils/errors\';',
    '',
    '/**',
    ' * PaymentController',
    ' * Handles all payment-related HTTP endpoints including creation,',
    ' * retrieval, refunds, and webhook processing for the Stripe integration.',
    ' */',
    'export class PaymentController {',
    '  private stripeService: StripeService;',
    '  private logger: Logger;',
    '  private notificationService: NotificationService;',
    '',
    '  constructor() {',
    '    this.stripeService = new StripeService(process.env.STRIPE_SECRET_KEY!);',
    '    this.logger = new Logger(\'PaymentController\');',
    '    this.notificationService = new NotificationService();',
    '  }',
    '',
    '  /**',
    '   * POST /api/payments',
    '   * Creates a new payment intent via Stripe and stores the record.',
    '   */',
    '  public async createPayment(req: Request, res: Response): Promise<Response> {',
    '    const { amount, currency, customerId, description, metadata } = req.body;',
    '',
    '    try {',
    '      this.logger.info(\'Creating payment intent\', { amount, currency, customerId });',
    '',
    '      // Validate amount',
    '      if (!amount || amount <= 0) {',
    '        throw new AppError(ErrorCode.VALIDATION, \'Amount must be a positive number\');',
    '      }',
    '',
    '      // Validate currency',
    '      const supportedCurrencies = [\'usd\', \'eur\', \'gbp\', \'jpy\', \'cad\', \'aud\'];',
    '      if (currency && !supportedCurrencies.includes(currency.toLowerCase())) {',
    '        throw new AppError(ErrorCode.VALIDATION, \'Unsupported currency: \' + currency);',
    '      }',
    '',
    '      // Verify customer exists in Stripe',
    '      if (customerId) {',
    '        const customer = await this.stripeService.getCustomer(customerId);',
    '        if (!customer) {',
    '          throw new AppError(ErrorCode.NOT_FOUND, \'Customer not found: \' + customerId);',
    '        }',
    '      }',
    '',
    '      // Create PaymentIntent via Stripe API',
    '      const paymentIntent = await this.stripeService.createPaymentIntent({',
    '        amount: Math.round(amount * 100), // Convert to cents',
    '        currency: currency || \'usd\',',
    '        customer: customerId,',
    '        description: description || \'Payment via API\',',
    '        metadata: {',
    '          source: \'api\',',
    '          ...metadata,',
    '        },',
    '        automatic_payment_methods: { enabled: true },',
    '      });',
    '',
    '      // Store payment record in database',
    '      const payment = await PaymentModel.create({',
    '        stripePaymentIntentId: paymentIntent.id,',
    '        amount,',
    '        currency: currency || \'usd\',',
    '        status: paymentIntent.status,',
    '        customerId: customerId || null,',
    '        description: description || \'Payment via API\',',
    '        metadata: metadata || {},',
    '        createdAt: new Date(),',
    '      });',
    '',
    '      this.logger.info(\'Payment intent created\', { paymentId: payment.id });',
    '',
    '      return res.status(201).json({',
    '        success: true,',
    '        data: {',
    '          id: payment.id,',
    '          clientSecret: paymentIntent.client_secret,',
    '          status: paymentIntent.status,',
    '          amount: payment.amount,',
    '          currency: payment.currency,',
    '        },',
    '      });',
    '    } catch (error) {',
    '      this.logger.error(\'Payment creation failed\', error);',
    '      if (error instanceof AppError) {',
    '        return res.status(error.statusCode).json({ success: false, error: error.message });',
    '      }',
    '      return res.status(500).json({ success: false, error: \'Payment processing failed\' });',
    '    }',
    '  }',
    '',
    '  /**',
    '   * GET /api/payments/:id',
    '   * Retrieves a single payment by its database ID.',
    '   */',
    '  public async getPayment(req: Request, res: Response): Promise<Response> {',
    '    const { id } = req.params;',
    '',
    '    try {',
    '      const payment = await PaymentModel.findById(id);',
    '      if (!payment) {',
    '        throw new AppError(ErrorCode.NOT_FOUND, \'Payment not found\');',
    '      }',
    '',
    '      // Fetch latest status from Stripe',
    '      const stripeIntent = await this.stripeService.getPaymentIntent(',
    '        payment.stripePaymentIntentId',
    '      );',
    '',
    '      // Sync status if changed',
    '      if (stripeIntent.status !== payment.status) {',
    '        payment.status = stripeIntent.status;',
    '        await payment.save();',
    '      }',
    '',
    '      return res.status(200).json({',
    '        success: true,',
    '        data: {',
    '          id: payment.id,',
    '          amount: payment.amount,',
    '          currency: payment.currency,',
    '          status: payment.status,',
    '          customerId: payment.customerId,',
    '          description: payment.description,',
    '          createdAt: payment.createdAt,',
    '          updatedAt: payment.updatedAt,',
    '        },',
    '      });',
    '    } catch (error) {',
    '      this.logger.error(\'Get payment failed\', error);',
    '      if (error instanceof AppError) {',
    '        return res.status(error.statusCode).json({ success: false, error: error.message });',
    '      }',
    '      return res.status(500).json({ success: false, error: \'Failed to retrieve payment\' });',
    '    }',
    '  }',
    '',
    '  /**',
    '   * GET /api/payments',
    '   * Lists all payments with optional filters and pagination.',
    '   */',
    '  public async listPayments(req: Request, res: Response): Promise<Response> {',
    '    const { status, customerId, page = 1, limit = 20 } = req.query;',
    '',
    '    try {',
    '      const filter: any = {};',
    '      if (status) filter.status = status;',
    '      if (customerId) filter.customerId = customerId;',
    '',
    '      const skip = (Number(page) - 1) * Number(limit);',
    '      const [payments, total] = await Promise.all([',
    '        PaymentModel.find(filter).skip(skip).limit(Number(limit)).sort({ createdAt: -1 }),',
    '        PaymentModel.countDocuments(filter),',
    '      ]);',
    '',
    '      return res.status(200).json({',
    '        success: true,',
    '        data: payments,',
    '        pagination: {',
    '          page: Number(page),',
    '          limit: Number(limit),',
    '          total,',
    '          totalPages: Math.ceil(total / Number(limit)),',
    '        },',
    '      });',
    '    } catch (error) {',
    '      this.logger.error(\'List payments failed\', error);',
    '      return res.status(500).json({ success: false, error: \'Failed to list payments\' });',
    '    }',
    '  }',
    '',
    '  /**',
    '   * POST /api/payments/:id/refund',
    '   * Initiates a full or partial refund for an existing payment.',
    '   */',
    '  public async refundPayment(req: Request, res: Response): Promise<Response> {',
    '    const { id } = req.params;',
    '    const { reason, amount: refundAmount } = req.body;',
    '',
    '    try {',
    '      const payment = await PaymentModel.findById(id);',
    '      if (!payment) {',
    '        throw new AppError(ErrorCode.NOT_FOUND, \'Payment not found\');',
    '      }',
    '',
    '      if (payment.status === \'refunded\') {',
    '        throw new AppError(ErrorCode.CONFLICT, \'Payment already refunded\');',
    '      }',
    '',
    '      if (payment.status !== \'succeeded\') {',
    '        throw new AppError(ErrorCode.VALIDATION, \'Only succeeded payments can be refunded\');',
    '      }',
    '',
    '      const refundParams: any = {',
    '        payment_intent: payment.stripePaymentIntentId,',
    '        reason: reason || \'requested_by_customer\',',
    '      };',
    '',
    '      // Support partial refunds',
    '      if (refundAmount && refundAmount < payment.amount) {',
    '        refundParams.amount = Math.round(refundAmount * 100);',
    '      }',
    '',
    '      const refund = await this.stripeService.createRefund(refundParams);',
    '',
    '      payment.status = refundAmount ? \'partially_refunded\' : \'refunded\';',
    '      payment.refundId = refund.id;',
    '      payment.refundedAt = new Date();',
    '      await payment.save();',
    '',
    '      // Send refund confirmation email',
    '      await this.notificationService.sendRefundConfirmation({',
    '        customerId: payment.customerId,',
    '        amount: refundAmount || payment.amount,',
    '        currency: payment.currency,',
    '        refundId: refund.id,',
    '      });',
    '',
    '      this.logger.info(\'Payment refunded\', { paymentId: id, refundId: refund.id });',
    '',
    '      return res.status(200).json({',
    '        success: true,',
    '        data: { refundId: refund.id, status: payment.status },',
    '      });',
    '    } catch (error) {',
    '      this.logger.error(\'Refund failed\', error);',
    '      if (error instanceof AppError) {',
    '        return res.status(error.statusCode).json({ success: false, error: error.message });',
    '      }',
    '      return res.status(500).json({ success: false, error: \'Refund processing failed\' });',
    '    }',
    '  }',
    '',
    '  /**',
    '   * POST /api/webhooks/stripe',
    '   * Handles incoming Stripe webhook events.',
    '   */',
    '  // TODO: Implement webhook signature verification',
    '  // TODO: Handle payment_intent.succeeded event',
    '  // TODO: Handle payment_intent.payment_failed event',
    '  // TODO: Send email notifications on payment status change',
    '}'
];

FILES["stripe.service.ts"] = [
    'import Stripe from \'stripe\';',
    'import { Logger } from \'../utils/logger\';',
    'import { AppError, ErrorCode } from \'../utils/errors\';',
    '',
    '/**',
    ' * StripeService',
    ' * Wraps the Stripe SDK to provide a clean interface for payment operations.',
    ' * Handles retries, error mapping, and logging for all Stripe API calls.',
    ' */',
    'export class StripeService {',
    '  private stripe: Stripe;',
    '  private logger: Logger;',
    '  private maxRetries: number = 3;',
    '',
    '  constructor(secretKey: string) {',
    '    if (!secretKey) {',
    '      throw new Error(\'STRIPE_SECRET_KEY is required\');',
    '    }',
    '',
    '    this.stripe = new Stripe(secretKey, {',
    '      apiVersion: \'2024-04-10\',',
    '      typescript: true,',
    '      maxNetworkRetries: this.maxRetries,',
    '    });',
    '',
    '    this.logger = new Logger(\'StripeService\');',
    '    this.logger.info(\'Stripe service initialized\');',
    '  }',
    '',
    '  /**',
    '   * Creates a new PaymentIntent in Stripe.',
    '   */',
    '  public async createPaymentIntent(',
    '    params: Stripe.PaymentIntentCreateParams',
    '  ): Promise<Stripe.PaymentIntent> {',
    '    try {',
    '      this.logger.debug(\'Creating PaymentIntent\', { amount: params.amount });',
    '      const intent = await this.stripe.paymentIntents.create(params);',
    '      this.logger.info(\'PaymentIntent created\', { id: intent.id, status: intent.status });',
    '      return intent;',
    '    } catch (error) {',
    '      this.handleStripeError(error, \'createPaymentIntent\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Retrieves an existing PaymentIntent by ID.',
    '   */',
    '  public async getPaymentIntent(id: string): Promise<Stripe.PaymentIntent> {',
    '    try {',
    '      return await this.stripe.paymentIntents.retrieve(id);',
    '    } catch (error) {',
    '      this.handleStripeError(error, \'getPaymentIntent\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Confirms a PaymentIntent with the given payment method.',
    '   */',
    '  public async confirmPaymentIntent(',
    '    id: string,',
    '    paymentMethodId: string',
    '  ): Promise<Stripe.PaymentIntent> {',
    '    try {',
    '      const intent = await this.stripe.paymentIntents.confirm(id, {',
    '        payment_method: paymentMethodId,',
    '      });',
    '      this.logger.info(\'PaymentIntent confirmed\', { id, status: intent.status });',
    '      return intent;',
    '    } catch (error) {',
    '      this.handleStripeError(error, \'confirmPaymentIntent\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Creates a refund for a PaymentIntent.',
    '   */',
    '  public async createRefund(',
    '    params: Stripe.RefundCreateParams',
    '  ): Promise<Stripe.Refund> {',
    '    try {',
    '      this.logger.debug(\'Creating refund\', params);',
    '      const refund = await this.stripe.refunds.create(params);',
    '      this.logger.info(\'Refund created\', { id: refund.id, status: refund.status });',
    '      return refund;',
    '    } catch (error) {',
    '      this.handleStripeError(error, \'createRefund\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Retrieves a Stripe Customer by ID.',
    '   */',
    '  public async getCustomer(customerId: string): Promise<Stripe.Customer | null> {',
    '    try {',
    '      const customer = await this.stripe.customers.retrieve(customerId);',
    '      if (customer.deleted) return null;',
    '      return customer as Stripe.Customer;',
    '    } catch (error: any) {',
    '      if (error.code === \'resource_missing\') return null;',
    '      this.handleStripeError(error, \'getCustomer\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Creates a new Stripe Customer.',
    '   */',
    '  public async createCustomer(',
    '    params: Stripe.CustomerCreateParams',
    '  ): Promise<Stripe.Customer> {',
    '    try {',
    '      const customer = await this.stripe.customers.create(params);',
    '      this.logger.info(\'Customer created\', { id: customer.id });',
    '      return customer;',
    '    } catch (error) {',
    '      this.handleStripeError(error, \'createCustomer\');',
    '      throw error;',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Verifies the signature of an incoming webhook event.',
    '   */',
    '  public verifyWebhookSignature(',
    '    payload: string | Buffer,',
    '    signature: string,',
    '    webhookSecret: string',
    '  ): Stripe.Event {',
    '    try {',
    '      return this.stripe.webhooks.constructEvent(payload, signature, webhookSecret);',
    '    } catch (error) {',
    '      this.logger.error(\'Webhook signature verification failed\', error);',
    '      throw new AppError(ErrorCode.UNAUTHORIZED, \'Invalid webhook signature\');',
    '    }',
    '  }',
    '',
    '  /**',
    '   * Maps Stripe errors to application-specific errors.',
    '   */',
    '  private handleStripeError(error: any, operation: string): void {',
    '    const stripeError = error as Stripe.errors.StripeError;',
    '    this.logger.error(operation + \' failed\', {',
    '      type: stripeError.type,',
    '      code: stripeError.code,',
    '      message: stripeError.message,',
    '    });',
    '',
    '    switch (stripeError.type) {',
    '      case \'StripeCardError\':',
    '        throw new AppError(ErrorCode.VALIDATION, stripeError.message);',
    '      case \'StripeRateLimitError\':',
    '        throw new AppError(ErrorCode.RATE_LIMIT, \'Too many requests to payment provider\');',
    '      case \'StripeInvalidRequestError\':',
    '        throw new AppError(ErrorCode.VALIDATION, stripeError.message);',
    '      case \'StripeAuthenticationError\':',
    '        throw new AppError(ErrorCode.UNAUTHORIZED, \'Payment provider auth failed\');',
    '      default:',
    '        throw new AppError(ErrorCode.INTERNAL, \'Payment provider error\');',
    '    }',
    '  }',
    '}'
];

FILES["payment.model.ts"] = [
    'import mongoose, { Schema, Document, Model } from \'mongoose\';',
    '',
    '/**',
    ' * IPayment Interface',
    ' * Defines the shape of a Payment document in MongoDB.',
    ' */',
    'export interface IPayment extends Document {',
    '  stripePaymentIntentId: string;',
    '  amount: number;',
    '  currency: string;',
    '  status: PaymentStatus;',
    '  customerId: string | null;',
    '  description: string;',
    '  metadata: Record<string, any>;',
    '  refundId?: string;',
    '  refundedAt?: Date;',
    '  createdAt: Date;',
    '  updatedAt: Date;',
    '}',
    '',
    'export type PaymentStatus =',
    '  | \'requires_payment_method\'',
    '  | \'requires_confirmation\'',
    '  | \'requires_action\'',
    '  | \'processing\'',
    '  | \'requires_capture\'',
    '  | \'canceled\'',
    '  | \'succeeded\'',
    '  | \'refunded\'',
    '  | \'partially_refunded\'',
    '  | \'failed\';',
    '',
    '/**',
    ' * Payment Schema',
    ' */',
    'const PaymentSchema = new Schema<IPayment>(',
    '  {',
    '    stripePaymentIntentId: {',
    '      type: String,',
    '      required: true,',
    '      unique: true,',
    '      index: true,',
    '    },',
    '    amount: {',
    '      type: Number,',
    '      required: true,',
    '      min: [0.01, \'Amount must be at least 0.01\'],',
    '    },',
    '    currency: {',
    '      type: String,',
    '      required: true,',
    '      lowercase: true,',
    '      enum: [\'usd\', \'eur\', \'gbp\', \'jpy\', \'cad\', \'aud\'],',
    '      default: \'usd\',',
    '    },',
    '    status: {',
    '      type: String,',
    '      required: true,',
    '      enum: [',
    '        \'requires_payment_method\',',
    '        \'requires_confirmation\',',
    '        \'requires_action\',',
    '        \'processing\',',
    '        \'requires_capture\',',
    '        \'canceled\',',
    '        \'succeeded\',',
    '        \'refunded\',',
    '        \'partially_refunded\',',
    '        \'failed\',',
    '      ],',
    '      default: \'requires_payment_method\',',
    '    },',
    '    customerId: {',
    '      type: String,',
    '      default: null,',
    '      index: true,',
    '    },',
    '    description: {',
    '      type: String,',
    '      default: \'\',',
    '    },',
    '    metadata: {',
    '      type: Schema.Types.Mixed,',
    '      default: {},',
    '    },',
    '    refundId: {',
    '      type: String,',
    '      default: null,',
    '    },',
    '    refundedAt: {',
    '      type: Date,',
    '      default: null,',
    '    },',
    '  },',
    '  {',
    '    timestamps: true,',
    '    toJSON: {',
    '      transform: (doc, ret) => {',
    '        ret.id = ret._id;',
    '        delete ret._id;',
    '        delete ret.__v;',
    '        return ret;',
    '      },',
    '    },',
    '  }',
    ');',
    '',
    '// Indexes for common queries',
    'PaymentSchema.index({ status: 1, createdAt: -1 });',
    'PaymentSchema.index({ customerId: 1, createdAt: -1 });',
    '',
    '// Static method: find by Stripe PaymentIntent ID',
    'PaymentSchema.statics.findByStripeId = function (',
    '  stripeId: string',
    '): Promise<IPayment | null> {',
    '  return this.findOne({ stripePaymentIntentId: stripeId });',
    '};',
    '',
    '// Static method: update payment status by Stripe ID',
    'PaymentSchema.statics.updateStatus = async function (',
    '  stripeId: string,',
    '  status: PaymentStatus',
    '): Promise<IPayment | null> {',
    '  return this.findOneAndUpdate(',
    '    { stripePaymentIntentId: stripeId },',
    '    { status, updatedAt: new Date() },',
    '    { new: true }',
    '  );',
    '};',
    '',
    '// Instance method: check if refundable',
    'PaymentSchema.methods.isRefundable = function (): boolean {',
    '  return this.status === \'succeeded\' && !this.refundId;',
    '};',
    '',
    '// Virtual for formatted amount',
    'PaymentSchema.virtual(\'formattedAmount\').get(function () {',
    '  const symbols: Record<string, string> = {',
    '    usd: \'$\', eur: \'\\u20ac\', gbp: \'\\u00a3\', jpy: \'\\u00a5\', cad: \'C$\', aud: \'A$\',',
    '  };',
    '  const symbol = symbols[this.currency] || this.currency.toUpperCase();',
    '  return symbol + this.amount.toFixed(2);',
    '});',
    '',
    'export const PaymentModel: Model<IPayment> = mongoose.model<IPayment>(\'Payment\', PaymentSchema);'
];

FILES["payment.validator.ts"] = [
    'import { Request, Response, NextFunction } from \'express\';',
    'import Joi from \'joi\';',
    'import { AppError, ErrorCode } from \'../utils/errors\';',
    'import { Logger } from \'../utils/logger\';',
    '',
    'const logger = new Logger(\'PaymentValidator\');',
    '',
    '/**',
    ' * Joi schemas for payment endpoint validation.',
    ' */',
    'const schemas = {',
    '  createPayment: Joi.object({',
    '    amount: Joi.number().positive().precision(2).required()',
    '      .messages({',
    '        \'number.positive\': \'Amount must be greater than zero\',',
    '        \'any.required\': \'Amount is required\',',
    '      }),',
    '    currency: Joi.string().lowercase().valid(\'usd\', \'eur\', \'gbp\', \'jpy\', \'cad\', \'aud\')',
    '      .default(\'usd\')',
    '      .messages({ \'any.only\': \'Unsupported currency\' }),',
    '    customerId: Joi.string().pattern(/^cus_/).optional()',
    '      .messages({ \'string.pattern.base\': \'Invalid customer ID format\' }),',
    '    description: Joi.string().max(500).optional(),',
    '    metadata: Joi.object().pattern(Joi.string(), Joi.string()).optional(),',
    '  }),',
    '',
    '  refundPayment: Joi.object({',
    '    reason: Joi.string().valid(',
    '      \'duplicate\',',
    '      \'fraudulent\',',
    '      \'requested_by_customer\'',
    '    ).default(\'requested_by_customer\'),',
    '    amount: Joi.number().positive().precision(2).optional()',
    '      .messages({ \'number.positive\': \'Refund amount must be positive\' }),',
    '  }),',
    '',
    '  listPayments: Joi.object({',
    '    status: Joi.string().valid(',
    '      \'succeeded\', \'failed\', \'refunded\', \'processing\', \'canceled\'',
    '    ).optional(),',
    '    customerId: Joi.string().pattern(/^cus_/).optional(),',
    '    page: Joi.number().integer().min(1).default(1),',
    '    limit: Joi.number().integer().min(1).max(100).default(20),',
    '    sortBy: Joi.string().valid(\'createdAt\', \'amount\', \'status\').default(\'createdAt\'),',
    '    sortOrder: Joi.string().valid(\'asc\', \'desc\').default(\'desc\'),',
    '  }),',
    '};',
    '',
    '/**',
    ' * Validation middleware factory.',
    ' * Takes a schema name and returns Express middleware that validates',
    ' * the request body (or query for GET) against the corresponding schema.',
    ' */',
    'export function validatePayment(schemaName: keyof typeof schemas) {',
    '  return (req: Request, res: Response, next: NextFunction): void => {',
    '    const schema = schemas[schemaName];',
    '    if (!schema) {',
    '      logger.error(\'Unknown validation schema\', { schemaName });',
    '      next(new AppError(ErrorCode.INTERNAL, \'Invalid validation schema\'));',
    '      return;',
    '    }',
    '',
    '    const dataToValidate = schemaName === \'listPayments\' ? req.query : req.body;',
    '',
    '    const { error, value } = schema.validate(dataToValidate, {',
    '      abortEarly: false,',
    '      stripUnknown: true,',
    '    });',
    '',
    '    if (error) {',
    '      const messages = error.details.map((d) => d.message).join(\'; \');',
    '      logger.warn(\'Validation failed\', { schemaName, errors: messages });',
    '      next(new AppError(ErrorCode.VALIDATION, messages));',
    '      return;',
    '    }',
    '',
    '    // Replace body/query with validated & sanitized values',
    '    if (schemaName === \'listPayments\') {',
    '      req.query = value;',
    '    } else {',
    '      req.body = value;',
    '    }',
    '',
    '    next();',
    '  };',
    '}',
    '',
    '/**',
    ' * Sanitizes string fields to prevent XSS in stored data.',
    ' */',
    'export function sanitizeInput(req: Request, _res: Response, next: NextFunction): void {',
    '  if (req.body && typeof req.body === \'object\') {',
    '    for (const key of Object.keys(req.body)) {',
    '      if (typeof req.body[key] === \'string\') {',
    '        req.body[key] = req.body[key]',
    '          .replace(/</g, \'&lt;\')',
    '          .replace(/>/g, \'&gt;\')',
    '          .replace(/"/g, \'&quot;\');',
    '      }',
    '    }',
    '  }',
    '  next();',
    '}'
];

FILES["auth.middleware.ts"] = [
    'import { Request, Response, NextFunction } from \'express\';',
    'import jwt from \'jsonwebtoken\';',
    'import { Logger } from \'../utils/logger\';',
    'import { AppError, ErrorCode } from \'../utils/errors\';',
    '',
    'const logger = new Logger(\'AuthMiddleware\');',
    '',
    'export interface AuthPayload {',
    '  userId: string;',
    '  email: string;',
    '  role: \'admin\' | \'user\' | \'merchant\';',
    '  merchantId?: string;',
    '}',
    '',
    'declare global {',
    '  namespace Express {',
    '    interface Request {',
    '      auth?: AuthPayload;',
    '    }',
    '  }',
    '}',
    '',
    '/**',
    ' * Verifies the JWT token in the Authorization header.',
    ' */',
    'export function authenticate(req: Request, _res: Response, next: NextFunction): void {',
    '  const authHeader = req.headers.authorization;',
    '',
    '  if (!authHeader || !authHeader.startsWith(\'Bearer \')) {',
    '    next(new AppError(ErrorCode.UNAUTHORIZED, \'Missing or invalid auth token\'));',
    '    return;',
    '  }',
    '',
    '  const token = authHeader.split(\' \')[1];',
    '',
    '  try {',
    '    const secret = process.env.JWT_SECRET;',
    '    if (!secret) {',
    '      throw new Error(\'JWT_SECRET not configured\');',
    '    }',
    '',
    '    const decoded = jwt.verify(token, secret) as AuthPayload;',
    '    req.auth = decoded;',
    '    logger.debug(\'Auth success\', { userId: decoded.userId, role: decoded.role });',
    '    next();',
    '  } catch (error: any) {',
    '    if (error.name === \'TokenExpiredError\') {',
    '      next(new AppError(ErrorCode.UNAUTHORIZED, \'Token expired\'));',
    '    } else if (error.name === \'JsonWebTokenError\') {',
    '      next(new AppError(ErrorCode.UNAUTHORIZED, \'Invalid token\'));',
    '    } else {',
    '      logger.error(\'Auth error\', error);',
    '      next(new AppError(ErrorCode.INTERNAL, \'Authentication failed\'));',
    '    }',
    '  }',
    '}',
    '',
    '/**',
    ' * Role-based access control middleware.',
    ' */',
    'export function authorize(...roles: string[]) {',
    '  return (req: Request, _res: Response, next: NextFunction): void => {',
    '    if (!req.auth) {',
    '      next(new AppError(ErrorCode.UNAUTHORIZED, \'Not authenticated\'));',
    '      return;',
    '    }',
    '',
    '    if (!roles.includes(req.auth.role)) {',
    '      logger.warn(\'Access denied\', {',
    '        userId: req.auth.userId,',
    '        role: req.auth.role,',
    '        requiredRoles: roles,',
    '      });',
    '      next(new AppError(ErrorCode.FORBIDDEN, \'Insufficient permissions\'));',
    '      return;',
    '    }',
    '',
    '    next();',
    '  };',
    '}',
    '',
    '/**',
    ' * Rate limiting per API key.',
    ' */',
    'const rateMap = new Map<string, { count: number; resetAt: number }>();',
    'const RATE_LIMIT = 100;',
    'const RATE_WINDOW_MS = 60 * 1000;',
    '',
    'export function rateLimit(req: Request, _res: Response, next: NextFunction): void {',
    '  const key = req.auth?.userId || req.ip || \'anonymous\';',
    '  const now = Date.now();',
    '  const entry = rateMap.get(key);',
    '',
    '  if (!entry || now > entry.resetAt) {',
    '    rateMap.set(key, { count: 1, resetAt: now + RATE_WINDOW_MS });',
    '    next();',
    '    return;',
    '  }',
    '',
    '  entry.count++;',
    '  if (entry.count > RATE_LIMIT) {',
    '    next(new AppError(ErrorCode.RATE_LIMIT, \'Rate limit exceeded. Try again later.\'));',
    '    return;',
    '  }',
    '',
    '  next();',
    '}'
];

FILES["notification.service.ts"] = [
    'import nodemailer from \'nodemailer\';',
    'import { Logger } from \'../utils/logger\';',
    '',
    'interface EmailOptions {',
    '  to: string;',
    '  subject: string;',
    '  html: string;',
    '}',
    '',
    'interface RefundNotification {',
    '  customerId: string;',
    '  amount: number;',
    '  currency: string;',
    '  refundId: string;',
    '}',
    '',
    'interface PaymentNotification {',
    '  customerId: string;',
    '  amount: number;',
    '  currency: string;',
    '  paymentId: string;',
    '  status: string;',
    '}',
    '',
    '/**',
    ' * NotificationService',
    ' * Handles sending transactional emails for payment events.',
    ' */',
    'export class NotificationService {',
    '  private transporter: nodemailer.Transporter;',
    '  private logger: Logger;',
    '  private fromAddress: string;',
    '',
    '  constructor() {',
    '    this.logger = new Logger(\'NotificationService\');',
    '    this.fromAddress = process.env.EMAIL_FROM || \'noreply@paymentapi.com\';',
    '',
    '    this.transporter = nodemailer.createTransport({',
    '      host: process.env.SMTP_HOST || \'smtp.gmail.com\',',
    '      port: Number(process.env.SMTP_PORT) || 587,',
    '      secure: false,',
    '      auth: {',
    '        user: process.env.SMTP_USER,',
    '        pass: process.env.SMTP_PASS,',
    '      },',
    '    });',
    '',
    '    this.logger.info(\'Notification service initialized\');',
    '  }',
    '',
    '  public async sendPaymentConfirmation(data: PaymentNotification): Promise<void> {',
    '    const html = this.buildPaymentEmailHtml(data, \'confirmed\');',
    '    await this.sendEmail({',
    '      to: await this.getCustomerEmail(data.customerId),',
    '      subject: \'Payment Confirmed — \' + this.formatAmount(data.amount, data.currency),',
    '      html,',
    '    });',
    '  }',
    '',
    '  public async sendPaymentFailure(data: PaymentNotification): Promise<void> {',
    '    const html = this.buildPaymentEmailHtml(data, \'failed\');',
    '    await this.sendEmail({',
    '      to: await this.getCustomerEmail(data.customerId),',
    '      subject: \'Payment Failed — Action Required\',',
    '      html,',
    '    });',
    '  }',
    '',
    '  public async sendRefundConfirmation(data: RefundNotification): Promise<void> {',
    '    const html = \'<h2>Refund Processed</h2>\' +',
    '      \'<p>Your refund of <strong>\' + this.formatAmount(data.amount, data.currency) +',
    '      \'</strong> has been processed.</p>\' +',
    '      \'<p>Refund ID: \' + data.refundId + \'</p>\' +',
    '      \'<p>Please allow 5-10 business days for the refund to appear.</p>\';',
    '',
    '    await this.sendEmail({',
    '      to: await this.getCustomerEmail(data.customerId),',
    '      subject: \'Refund Processed — \' + this.formatAmount(data.amount, data.currency),',
    '      html,',
    '    });',
    '  }',
    '',
    '  private async sendEmail(options: EmailOptions): Promise<void> {',
    '    try {',
    '      await this.transporter.sendMail({',
    '        from: this.fromAddress,',
    '        to: options.to,',
    '        subject: options.subject,',
    '        html: options.html,',
    '      });',
    '      this.logger.info(\'Email sent\', { to: options.to, subject: options.subject });',
    '    } catch (error) {',
    '      this.logger.error(\'Failed to send email\', error);',
    '    }',
    '  }',
    '',
    '  private buildPaymentEmailHtml(data: PaymentNotification, type: string): string {',
    '    const amount = this.formatAmount(data.amount, data.currency);',
    '    if (type === \'confirmed\') {',
    '      return \'<h2>Payment Confirmed</h2><p>Amount: <strong>\' + amount + \'</strong></p>\' +',
    '        \'<p>Payment ID: \' + data.paymentId + \'</p><p>Thank you for your payment!</p>\';',
    '    }',
    '    return \'<h2>Payment Failed</h2><p>Amount: <strong>\' + amount + \'</strong></p>\' +',
    '      \'<p>Please update your payment method and try again.</p>\';',
    '  }',
    '',
    '  private formatAmount(amount: number, currency: string): string {',
    '    const symbols: Record<string, string> = {',
    '      usd: \'$\', eur: \'\\u20ac\', gbp: \'\\u00a3\', jpy: \'\\u00a5\',',
    '    };',
    '    return (symbols[currency] || currency.toUpperCase() + \' \') + amount.toFixed(2);',
    '  }',
    '',
    '  private async getCustomerEmail(customerId: string): Promise<string> {',
    '    // In production, fetch from DB or Stripe',
    '    return \'customer@example.com\';',
    '  }',
    '}'
];

FILES["app.ts"] = [
    'import express from \'express\';',
    'import cors from \'cors\';',
    'import helmet from \'helmet\';',
    'import morgan from \'morgan\';',
    'import mongoose from \'mongoose\';',
    'import { PaymentController } from \'./controllers/payment.controller\';',
    'import { validatePayment, sanitizeInput } from \'./middleware/payment.validator\';',
    'import { authenticate, authorize, rateLimit } from \'./middleware/auth.middleware\';',
    'import { errorHandler } from \'./middleware/error.handler\';',
    'import { Logger } from \'./utils/logger\';',
    '',
    'const logger = new Logger(\'App\');',
    'const app = express();',
    '',
    '// ===== Global Middleware =====',
    'app.use(helmet());',
    'app.use(cors({ origin: process.env.ALLOWED_ORIGINS?.split(\',\') || [\'*\'] }));',
    'app.use(morgan(\'combined\'));',
    'app.use(express.json({ limit: \'10mb\' }));',
    'app.use(sanitizeInput);',
    '',
    '// ===== Database Connection =====',
    'const MONGO_URI = process.env.MONGODB_URI || \'mongodb://localhost:27017/payment-api\';',
    '',
    'mongoose.connect(MONGO_URI)',
    '  .then(() => logger.info(\'Connected to MongoDB\', { uri: MONGO_URI }))',
    '  .catch((err) => {',
    '    logger.error(\'MongoDB connection failed\', err);',
    '    process.exit(1);',
    '  });',
    '',
    '// ===== Routes =====',
    'const paymentController = new PaymentController();',
    '',
    '// Health check',
    'app.get(\'/health\', (_req, res) => {',
    '  res.json({ status: \'ok\', timestamp: new Date().toISOString() });',
    '});',
    '',
    '// Payment routes (authenticated)',
    'app.post(',
    '  \'/api/payments\',',
    '  authenticate,',
    '  rateLimit,',
    '  validatePayment(\'createPayment\'),',
    '  paymentController.createPayment.bind(paymentController)',
    ');',
    '',
    'app.get(',
    '  \'/api/payments\',',
    '  authenticate,',
    '  validatePayment(\'listPayments\'),',
    '  paymentController.listPayments.bind(paymentController)',
    ');',
    '',
    'app.get(',
    '  \'/api/payments/:id\',',
    '  authenticate,',
    '  paymentController.getPayment.bind(paymentController)',
    ');',
    '',
    'app.post(',
    '  \'/api/payments/:id/refund\',',
    '  authenticate,',
    '  authorize(\'admin\', \'merchant\'),',
    '  validatePayment(\'refundPayment\'),',
    '  paymentController.refundPayment.bind(paymentController)',
    ');',
    '',
    '// Stripe webhook (no auth — uses signature verification)',
    'app.post(',
    '  \'/api/webhooks/stripe\',',
    '  express.raw({ type: \'application/json\' }),',
    '  // paymentController.handleWebhook.bind(paymentController) // TODO',
    ');',
    '',
    '// ===== Error Handler =====',
    'app.use(errorHandler);',
    '',
    '// ===== Start Server =====',
    'const PORT = Number(process.env.PORT) || 3000;',
    '',
    'app.listen(PORT, () => {',
    '  logger.info(\'Server started\', { port: PORT, env: process.env.NODE_ENV });',
    '});',
    '',
    'export default app;'
];

FILES["logger.ts"] = [
    'import winston from \'winston\';',
    '',
    'const { combine, timestamp, printf, colorize, errors } = winston.format;',
    '',
    'const logFormat = printf(({ level, message, timestamp, context, ...meta }) => {',
    '  const ctx = context ? \'[\' + context + \'] \' : \'\';',
    '  const metaStr = Object.keys(meta).length ? \' \' + JSON.stringify(meta) : \'\';',
    '  return timestamp + \' \' + level + \': \' + ctx + message + metaStr;',
    '});',
    '',
    'const winstonLogger = winston.createLogger({',
    '  level: process.env.LOG_LEVEL || \'info\',',
    '  format: combine(',
    '    errors({ stack: true }),',
    '    timestamp({ format: \'YYYY-MM-DD HH:mm:ss\' }),',
    '    logFormat',
    '  ),',
    '  transports: [',
    '    new winston.transports.Console({',
    '      format: combine(colorize(), logFormat),',
    '    }),',
    '    new winston.transports.File({',
    '      filename: \'logs/error.log\',',
    '      level: \'error\',',
    '      maxsize: 5242880,',
    '      maxFiles: 5,',
    '    }),',
    '    new winston.transports.File({',
    '      filename: \'logs/combined.log\',',
    '      maxsize: 5242880,',
    '      maxFiles: 5,',
    '    }),',
    '  ],',
    '});',
    '',
    '/**',
    ' * Logger class wrapping winston for contextualized logging.',
    ' */',
    'export class Logger {',
    '  private context: string;',
    '',
    '  constructor(context: string) {',
    '    this.context = context;',
    '  }',
    '',
    '  info(message: string, meta?: any): void {',
    '    winstonLogger.info(message, { context: this.context, ...meta });',
    '  }',
    '',
    '  warn(message: string, meta?: any): void {',
    '    winstonLogger.warn(message, { context: this.context, ...meta });',
    '  }',
    '',
    '  error(message: string, meta?: any): void {',
    '    winstonLogger.error(message, { context: this.context, ...meta });',
    '  }',
    '',
    '  debug(message: string, meta?: any): void {',
    '    winstonLogger.debug(message, { context: this.context, ...meta });',
    '  }',
    '}'
];

FILES["errors.ts"] = [
    '/**',
    ' * Application error codes mapped to HTTP status codes.',
    ' */',
    'export enum ErrorCode {',
    '  VALIDATION = 400,',
    '  UNAUTHORIZED = 401,',
    '  FORBIDDEN = 403,',
    '  NOT_FOUND = 404,',
    '  CONFLICT = 409,',
    '  RATE_LIMIT = 429,',
    '  INTERNAL = 500,',
    '}',
    '',
    '/**',
    ' * Custom application error with HTTP status code support.',
    ' */',
    'export class AppError extends Error {',
    '  public readonly statusCode: number;',
    '  public readonly isOperational: boolean;',
    '',
    '  constructor(',
    '    statusCode: ErrorCode,',
    '    message: string,',
    '    isOperational: boolean = true',
    '  ) {',
    '    super(message);',
    '    this.statusCode = statusCode;',
    '    this.isOperational = isOperational;',
    '    Object.setPrototypeOf(this, AppError.prototype);',
    '    Error.captureStackTrace(this, this.constructor);',
    '  }',
    '}',
    '',
    '/**',
    ' * Error handler middleware for Express.',
    ' */',
    'export function errorHandler(err: any, _req: any, res: any, _next: any): void {',
    '  if (err instanceof AppError) {',
    '    res.status(err.statusCode).json({',
    '      success: false,',
    '      error: err.message,',
    '    });',
    '    return;',
    '  }',
    '',
    '  // Mongoose validation error',
    '  if (err.name === \'ValidationError\') {',
    '    const messages = Object.values(err.errors).map((e: any) => e.message).join(\'; \');',
    '    res.status(400).json({ success: false, error: messages });',
    '    return;',
    '  }',
    '',
    '  // Mongoose duplicate key',
    '  if (err.code === 11000) {',
    '    res.status(409).json({ success: false, error: \'Duplicate record\' });',
    '    return;',
    '  }',
    '',
    '  // Unknown error',
    '  console.error(\'Unhandled error:\', err);',
    '  res.status(500).json({ success: false, error: \'Internal server error\' });',
    '}'
];

FILES["package.json"] = [
    '{',
    '  "name": "payment-api",',
    '  "version": "1.0.0",',
    '  "description": "Stripe Payment Processing API",',
    '  "main": "dist/app.js",',
    '  "scripts": {',
    '    "dev": "ts-node-dev --respawn src/app.ts",',
    '    "build": "tsc",',
    '    "start": "node dist/app.js",',
    '    "test": "jest --coverage",',
    '    "lint": "eslint src/ --ext .ts"',
    '  },',
    '  "dependencies": {',
    '    "cors": "^2.8.5",',
    '    "express": "^4.18.2",',
    '    "helmet": "^7.1.0",',
    '    "joi": "^17.11.0",',
    '    "jsonwebtoken": "^9.0.2",',
    '    "mongoose": "^8.0.3",',
    '    "morgan": "^1.10.0",',
    '    "nodemailer": "^6.9.7",',
    '    "stripe": "^14.8.0",',
    '    "winston": "^3.11.0"',
    '  },',
    '  "devDependencies": {',
    '    "@types/express": "^4.17.21",',
    '    "@types/cors": "^2.8.17",',
    '    "@types/jsonwebtoken": "^9.0.5",',
    '    "@types/morgan": "^1.9.9",',
    '    "@types/nodemailer": "^6.4.14",',
    '    "ts-node-dev": "^2.0.0",',
    '    "typescript": "^5.3.2",',
    '    "jest": "^29.7.0",',
    '    "ts-jest": "^29.1.1"',
    '  }',
    '}'
];

FILES["tsconfig.json"] = [
    '{',
    '  "compilerOptions": {',
    '    "target": "ES2020",',
    '    "module": "commonjs",',
    '    "lib": ["ES2020"],',
    '    "outDir": "./dist",',
    '    "rootDir": "./src",',
    '    "strict": true,',
    '    "esModuleInterop": true,',
    '    "skipLibCheck": true,',
    '    "forceConsistentCasingInFileNames": true,',
    '    "resolveJsonModule": true,',
    '    "declaration": true,',
    '    "declarationMap": true,',
    '    "sourceMap": true',
    '  },',
    '  "include": ["src/**/*"],',
    '  "exclude": ["node_modules", "dist", "**/*.test.ts"]',
    '}'
];

FILES[".env"] = [
    '# Server',
    'PORT=3000',
    'NODE_ENV=development',
    '',
    '# MongoDB',
    'MONGODB_URI=mongodb://localhost:27017/payment-api',
    '',
    '# Stripe',
    'STRIPE_SECRET_KEY=sk_test_51N...',
    'STRIPE_WEBHOOK_SECRET=whsec_...',
    '',
    '# JWT',
    'JWT_SECRET=your-super-secret-jwt-key-change-in-production',
    'JWT_EXPIRES_IN=24h',
    '',
    '# Email (SMTP)',
    'SMTP_HOST=smtp.gmail.com',
    'SMTP_PORT=587',
    'SMTP_USER=your-email@gmail.com',
    'SMTP_PASS=your-app-password',
    'EMAIL_FROM=noreply@paymentapi.com',
    '',
    '# Logging',
    'LOG_LEVEL=info',
    '',
    '# CORS',
    'ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173'
];

// File metadata for the explorer
var FILE_TREE = [
    { name: "payment-api", type: "folder", depth: 0 },
    { name: "src", type: "folder", depth: 1 },
    { name: "controllers", type: "folder", depth: 2 },
    { name: "payment.controller.ts", type: "ts", depth: 3 },
    { name: "webhook.controller.ts", type: "ts", depth: 3 },
    { name: "services", type: "folder", depth: 2 },
    { name: "stripe.service.ts", type: "ts", depth: 3 },
    { name: "notification.service.ts", type: "ts", depth: 3 },
    { name: "middleware", type: "folder", depth: 2 },
    { name: "payment.validator.ts", type: "ts", depth: 3 },
    { name: "auth.middleware.ts", type: "ts", depth: 3 },
    { name: "models", type: "folder", depth: 2 },
    { name: "payment.model.ts", type: "ts", depth: 3 },
    { name: "utils", type: "folder", depth: 2 },
    { name: "logger.ts", type: "ts", depth: 3 },
    { name: "errors.ts", type: "ts", depth: 3 },
    { name: "app.ts", type: "ts", depth: 2 },
    { name: "package.json", type: "json", depth: 1 },
    { name: "tsconfig.json", type: "json", depth: 1 },
    { name: ".env", type: "env", depth: 1 },
];

// Count total lines
var totalLines = 0;
for (var key in FILES) {
    totalLines += FILES[key].length;
}
